# Generated by Django 2.2 on 2019-04-06 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 4, 6, 22, 19, 4, 226924)),
        ),
    ]
